### ISSUE TITLE
Shift+Tab in a cell that contains a list produces invalid results

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-table#136] opened 2018-10-04 06:55 UTC
You can _iterate_ through the cells using <kbd>Tab</kbd> key. If you want to back to a previous cell, use combination of <kbd>Shift</kbd> + <kbd>Tab</kbd>.

If a cell contain a list, instead of going back, the list is being removed. After pressing <kbd>Shift</kbd> + <kbd>Tab</kbd> again, I'm going to previous cell.

![safari-list-and-keyboard-nav](https://user-images.githubusercontent.com/2270764/46457394-796b9580-c7b2-11e8-8512-be3a16a89f59.gif)

I can reproduce in on Chrome and Safari.

**Comment by jodator** [comment] 2018-10-04 08:30
AFAIR it is was by design. You always have arrows to navigate.

cc @Reinmar

**Comment by Reinmar** [comment] 2018-10-04 09:02
That's not handled by us, right? AFAIR it's the browser's behaviour. 

Also, <kbd>Tab</kbd> should not be used for navigating through such things at all. <kbd>Tab</kbd> should leave the editor and move to the next focusable thing on the page. So that's an a11y issue but of a much bigger scope.

I'd close this ticket and report a proper ticket that <kbd>Tab</kbd> must be handled differently in general. 

cc @oleq could you re-report it?

**Comment by jodator** [comment] 2018-10-04 09:12
> That's not handled by us, right? AFAIR it's the browser's behaviour.

No. It is handled and implemented by us. The <kbd>tab</kbd> and <kbd>shift</kbd>+<kbd>tab</kbd>.

Also we have talks that the inner most feature should handle <kbd>tab</kbd> so it does in here.

**Comment by jodator** [comment] 2018-10-04 09:13
ps.: and there's <kbd>tab</kbd> in the last table cell which creates another table row.

**Comment by Reinmar** [comment] 2018-10-04 09:36
Doh, so it'll be harder to make a decision about the behaviour. The safe direction may be to copy from CKEditor 4. How does it work there?

**Comment by jodator** [comment] 2018-10-04 09:53
@Reinmar: From the https://github.com/ckeditor/ckeditor5-table/issues/7#issuecomment-380384235:
> As for CKE4:
> - the TAB in the last cell creates another row
> - the SHIFT-TAB on the first table cell doesn't do anything (the caret stays there)
> - the arrows movement is as in browser (so Chrome & Firefox acts differently on up/down)

**Comment by Reinmar** [comment] 2019-04-16 11:03
Moved to https://github.com/ckeditor/ckeditor5-table/issues/183.

**Closed by Reinmar** 2019-04-16 11:03 UTC
Labels: type:bug
