### ISSUE TITLE
Can't go to the next line in table cell

### ISSUE THREAD

**Issue by dmitrykinakh** [ckeditor/ckeditor5-table#54] opened 2018-06-14 08:19 UTC
See the video: https://monosnap.com/file/b3kN8kCL0oPfJBhS3Ly2W8DQxM9ko6

**Comment by oleq** [comment] 2018-06-14 12:11
A duplicate of https://github.com/ckeditor/ckeditor5-table/issues/56.

**Closed by oleq** 2018-06-14 12:11 UTC
