### ISSUE TITLE
Page will be crashed if I'll do right click

### ISSUE THREAD

**Issue by dmitrykinakh** [ckeditor/ckeditor5-table#49] opened 2018-06-13 12:16 UTC
See the video: http://take.ms/maq61

Also, I'm attaching source code of that table which might help you guys to determine an issue.
[table_crash.txt](https://github.com/ckeditor/ckeditor5-table/files/2098025/table_crash.txt)

**Comment by Reinmar** [comment] 2018-06-13 12:19
@jodator, it seems to be related to https://github.com/ckeditor/ckeditor5-table/issues/11

I think we need to report it to Chrome. Naturally, a browser crash is not a problem on our side.

**Comment by jodator** [comment] 2018-06-13 12:21
@Reinmar yeah it looks like it's the case - anyway the https://github.com/ckeditor/ckeditor5-table/pull/39 fixes the #11 AFAICS so this one might be fixed also.

**Comment by jodator** [comment] 2018-06-13 12:32
@Reinmar: I cannot reproduce it on `t/12` branch while on master I can.

**Comment by dmitrykinakh** [comment] 2018-06-13 12:37
@Reinmar, we have much more work to do with CKEditor 5. Table feature is only one small thing we have added. The next one probably would be collaborative editing.

PS: Hello from Lutsk, Ukraine ;-)

**Comment by dmitrykinakh** [comment] 2018-06-14 13:32
@jodator, @Reinmar  - I still can reproduce this in Chrome (not in Firefox) even I'm using t/12 branch.
But now I've strict steps how I can reproduce this, see the video - http://take.ms/HRG82

**Comment by Reinmar** [comment] 2018-06-14 13:39
The clue of this change is in https://github.com/ckeditor/ckeditor5-engine/pull/1431. Which is not merged yet (unlike the PR in ckeditor5-table). You would need to check it with the changes in ckeditor5-engine.

**Comment by jodator** [comment] 2018-06-14 13:40
@dmitrykinakh You should use also branch `t/ckeditor5-table/12` in ckeditor5-engine as the actual fix is there. It's going to land on master in the matter of days.

**Closed** 2018-06-29 06:48 UTC
